# coding: utf-8

"""
    Kagi API

    The search API provides programmatic access to data that powers our search results & more. Kagi APIs  We have the following APIs available. ### Commercial  - Kagi Search API (invite only at the moment) - Web and News Enrichment API (public, exposes Kagi's own indexes Teclis and TinyGem) - Universal Summarizer API (public) - FastGPT API (public)  Quick start for all APIs:  - Get the API key (requires a Kagi account). - Top off your API credits. - Call the API.  ### Free  - Kagi Small Web RSS feed (public)  ### Unofficial Client Libraries  Libraries created by Kagi users and third parties.  - kagigo for Go - FastGPT & Universal Summarizer - kagi-api for Rust - kagi-dotnet for C#/.NET  ### Beta Status  The API is currently in a \"v0\" beta status. Changes will be ongoing, and will be added to the documentation below as features become available.  Use at your own risk, but please reach out to us if you have any questions.  See the Support and Community section for details. ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - Bug Reports - Q&A Forum - API Feature Requests  ### Discord Join our Discord! Good for quick questions, chatting about thing you've made with our APIs! 

    The version of the OpenAPI document: 0.0.0
    Contact: support@kagi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.translate_proof_read_get200_response import TranslateProofReadGet200Response

class TestTranslateProofReadGet200Response(unittest.TestCase):
    """TranslateProofReadGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TranslateProofReadGet200Response:
        """Test TranslateProofReadGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TranslateProofReadGet200Response`
        """
        model = TranslateProofReadGet200Response()
        if include_optional:
            return TranslateProofReadGet200Response(
                corrected_text = '',
                detected_language = openapi_client.models.translate_proof_read_get_200_response_detected_language.translateProofReadGet_200_response_detected_language(
                    iso = '', 
                    label = '', ),
                changes = [
                    openapi_client.models.translate_proof_read_get_200_response_changes_inner.translateProofReadGet_200_response_changes_inner(
                        original = '', 
                        correction = '', 
                        explanation = '', 
                        types = [
                            ''
                            ], 
                        severity = 'high', )
                    ],
                corrections_summary = '',
                tone_analysis = openapi_client.models.translate_proof_read_get_200_response_tone_analysis.translateProofReadGet_200_response_tone_analysis(
                    overall_tone = '', 
                    description = '', 
                    suggestions = '', ),
                voice_consistency = openapi_client.models.translate_proof_read_get_200_response_voice_consistency.translateProofReadGet_200_response_voice_consistency(
                    active_voice_percentage = 1.337, 
                    passive_voice_percentage = 1.337, 
                    is_consistent = True, 
                    suggestion = '', 
                    passive_instances = [
                        openapi_client.models.translate_proof_read_get_200_response_voice_consistency_passive_instances_inner.translateProofReadGet_200_response_voice_consistency_passive_instances_inner(
                            passive = '', 
                            active_alternative = '', )
                        ], 
                    summary = '', ),
                repetition_detection = openapi_client.models.translate_proof_read_get_200_response_repetition_detection.translateProofReadGet_200_response_repetition_detection(
                    repeated_words = [
                        openapi_client.models.translate_proof_read_get_200_response_repetition_detection_repeated_words_inner.translateProofReadGet_200_response_repetition_detection_repeated_words_inner(
                            word = '', 
                            significance = '', )
                        ], 
                    repeated_phrases = [
                        openapi_client.models.translate_proof_read_get_200_response_repetition_detection_repeated_phrases_inner.translateProofReadGet_200_response_repetition_detection_repeated_phrases_inner(
                            phrase = '', 
                            significance = '', )
                        ], 
                    summary = '', ),
                explanation_language = ''
            )
        else:
            return TranslateProofReadGet200Response(
        )
        """

    def testTranslateProofReadGet200Response(self):
        """Test TranslateProofReadGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
