# coding: utf-8

"""
    Kagi API

    The search API provides programmatic access to data that powers our search results & more. Kagi APIs  We have the following APIs available. ### Commercial  - Kagi Search API (invite only at the moment) - Web and News Enrichment API (public, exposes Kagi's own indexes Teclis and TinyGem) - Universal Summarizer API (public) - FastGPT API (public)  Quick start for all APIs:  - Get the API key (requires a Kagi account). - Top off your API credits. - Call the API.  ### Free  - Kagi Small Web RSS feed (public)  ### Unofficial Client Libraries  Libraries created by Kagi users and third parties.  - kagigo for Go - FastGPT & Universal Summarizer - kagi-api for Rust - kagi-dotnet for C#/.NET  ### Beta Status  The API is currently in a \"v0\" beta status. Changes will be ongoing, and will be added to the documentation below as features become available.  Use at your own risk, but please reach out to us if you have any questions.  See the Support and Community section for details. ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - Bug Reports - Q&A Forum - API Feature Requests  ### Discord Join our Discord! Good for quick questions, chatting about thing you've made with our APIs! 

    The version of the OpenAPI document: 0.0.0
    Contact: support@kagi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.translate_api import TranslateApi


class TestTranslateApi(unittest.TestCase):
    """TranslateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TranslateApi()

    def tearDown(self) -> None:
        pass

    def test_translate_alternatives(self) -> None:
        """Test case for translate_alternatives

        Alternative Translations
        """
        pass

    def test_translate_detect(self) -> None:
        """Test case for translate_detect

        Language Detection
        """
        pass

    def test_translate_detect_get(self) -> None:
        """Test case for translate_detect_get

        Language Detection API
        """
        pass

    def test_translate_dictionary(self) -> None:
        """Test case for translate_dictionary

        Dictionary
        """
        pass

    def test_translate_file(self) -> None:
        """Test case for translate_file

        File Translation
        """
        pass

    def test_translate_list_languages(self) -> None:
        """Test case for translate_list_languages

        List Supported Languages
        """
        pass

    def test_translate_list_languages_post(self) -> None:
        """Test case for translate_list_languages_post

        List Supported Languages API (POST method)
        """
        pass

    def test_translate_proof_read(self) -> None:
        """Test case for translate_proof_read

        Text Proofreading
        """
        pass

    def test_translate_proof_read_get(self) -> None:
        """Test case for translate_proof_read_get

        Text Proofreading API
        """
        pass

    def test_translate_romanize(self) -> None:
        """Test case for translate_romanize

        Text Romanization
        """
        pass

    def test_translate_speech(self) -> None:
        """Test case for translate_speech

        Text-to-Speech
        """
        pass

    def test_translate_text_alignments(self) -> None:
        """Test case for translate_text_alignments

        Text Alignments
        """
        pass

    def test_translate_transacribe(self) -> None:
        """Test case for translate_transacribe

        Audio Transcription
        """
        pass

    def test_translate_word_insights(self) -> None:
        """Test case for translate_word_insights

        Word Insights
        """
        pass


if __name__ == '__main__':
    unittest.main()
