# coding: utf-8

"""
    Kagi API

    The search API provides programmatic access to data that powers our search results & more. Kagi APIs  We have the following APIs available. ### Commercial  - Kagi Search API (invite only at the moment) - Web and News Enrichment API (public, exposes Kagi's own indexes Teclis and TinyGem) - Universal Summarizer API (public) - FastGPT API (public)  Quick start for all APIs:  - Get the API key (requires a Kagi account). - Top off your API credits. - Call the API.  ### Free  - Kagi Small Web RSS feed (public)  ### Unofficial Client Libraries  Libraries created by Kagi users and third parties.  - kagigo for Go - FastGPT & Universal Summarizer - kagi-api for Rust - kagi-dotnet for C#/.NET  ### Beta Status  The API is currently in a \"v0\" beta status. Changes will be ongoing, and will be added to the documentation below as features become available.  Use at your own risk, but please reach out to us if you have any questions.  See the Support and Community section for details. ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - Bug Reports - Q&A Forum - API Feature Requests  ### Discord Join our Discord! Good for quick questions, chatting about thing you've made with our APIs! 

    The version of the OpenAPI document: 0.0.0
    Contact: support@kagi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.super_search200_response import SuperSearch200Response

class TestSuperSearch200Response(unittest.TestCase):
    """SuperSearch200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuperSearch200Response:
        """Test SuperSearch200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuperSearch200Response`
        """
        model = SuperSearch200Response()
        if include_optional:
            return SuperSearch200Response(
                meta = openapi_client.models.v1_meta.v1Meta(
                    trace = '', 
                    node = '', 
                    ms = 56, 
                    query = openapi_client.models.v1_meta_query.v1Meta_query(
                        raw = '', 
                        terms = '', 
                        fields = [
                            openapi_client.models.v1_meta_query_fields_inner.v1Meta_query_fields_inner(
                                kind = '', 
                                value = '', 
                                name = '', 
                                negate = True, )
                            ], 
                        workflow = '', ), ),
                data = openapi_client.models.super_search_200_response_data.superSearch_200_response_data(
                    search = [
                        openapi_client.models.v1_result_search.v1ResultSearch(
                            url = '', 
                            title = '', 
                            snippet = '', 
                            time = '', 
                            image = openapi_client.models.v1_result_search_image.v1ResultSearch_image(
                                url = '', 
                                height = 56, 
                                width = 56, ), 
                            props = openapi_client.models.v1_result_search_props.v1ResultSearch_props(
                                thumbnail_image = openapi_client.models.v1_result_search_props_thumbnail_image.v1ResultSearch_props_thumbnail_image(
                                    url = '', 
                                    height = 56, 
                                    width = 56, ), 
                                language = '', 
                                language_probability = 56, 
                                paywalled = True, 
                                sort_normalize_url = '', 
                                sort_group_id = '', 
                                source_history = [
                                    ''
                                    ], ), )
                        ], 
                    video = [
                        openapi_client.models.v1_result_video.v1ResultVideo(
                            url = '', 
                            title = '', 
                            snippet = '', 
                            time = '', )
                        ], 
                    adjacent_question = [
                        openapi_client.models.v1_result_adjacent_question.v1ResultAdjacentQuestion(
                            url = '', 
                            title = '', 
                            snippet = '', 
                            time = '', )
                        ], 
                    infobox = [
                        openapi_client.models.v1_result_infobox.v1ResultInfobox(
                            url = '', 
                            title = '', 
                            snippet = '', 
                            time = '', )
                        ], 
                    web_archive = [
                        openapi_client.models.v1_result_web_archive.v1ResultWebArchive(
                            url = '', 
                            title = '', 
                            snippet = '', 
                            time = '', )
                        ], )
            )
        else:
            return SuperSearch200Response(
        )
        """

    def testSuperSearch200Response(self):
        """Test SuperSearch200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
