# coding: utf-8

# flake8: noqa
"""
    Kagi API

    The search API provides programmatic access to data that powers our search results & more. Kagi APIs  We have the following APIs available. ### Commercial  - Kagi Search API (invite only at the moment) - Web and News Enrichment API (public, exposes Kagi's own indexes Teclis and TinyGem) - Universal Summarizer API (public) - FastGPT API (public)  Quick start for all APIs:  - Get the API key (requires a Kagi account). - Top off your API credits. - Call the API.  ### Free  - Kagi Small Web RSS feed (public)  ### Unofficial Client Libraries  Libraries created by Kagi users and third parties.  - kagigo for Go - FastGPT & Universal Summarizer - kagi-api for Rust - kagi-dotnet for C#/.NET  ### Beta Status  The API is currently in a \"v0\" beta status. Changes will be ongoing, and will be added to the documentation below as features become available.  Use at your own risk, but please reach out to us if you have any questions.  See the Support and Community section for details. ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - Bug Reports - Q&A Forum - API Feature Requests  ### Discord Join our Discord! Good for quick questions, chatting about thing you've made with our APIs! 

    The version of the OpenAPI document: 0.0.0
    Contact: support@kagi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.enrich_search200_response import EnrichSearch200Response
from openapi_client.models.example_error import ExampleError
from openapi_client.models.example_error_error import ExampleErrorError
from openapi_client.models.fast_gpt200_response import FastGPT200Response
from openapi_client.models.fast_gpt200_response_data import FastGPT200ResponseData
from openapi_client.models.fast_gpt_request import FastGPTRequest
from openapi_client.models.meta import Meta
from openapi_client.models.search200_response import Search200Response
from openapi_client.models.search200_response_data_inner import Search200ResponseDataInner
from openapi_client.models.search_object import SearchObject
from openapi_client.models.search_related import SearchRelated
from openapi_client.models.summary import Summary
from openapi_client.models.summary_data import SummaryData
from openapi_client.models.super_search200_response import SuperSearch200Response
from openapi_client.models.super_search200_response_data import SuperSearch200ResponseData
from openapi_client.models.super_search_request import SuperSearchRequest
from openapi_client.models.upload_text import UploadText
from openapi_client.models.v1_meta import V1Meta
from openapi_client.models.v1_meta_query import V1MetaQuery
from openapi_client.models.v1_meta_query_fields_inner import V1MetaQueryFieldsInner
from openapi_client.models.v1_result_adjacent_question import V1ResultAdjacentQuestion
from openapi_client.models.v1_result_adjacent_question_props import V1ResultAdjacentQuestionProps
from openapi_client.models.v1_result_infobox import V1ResultInfobox
from openapi_client.models.v1_result_infobox_props import V1ResultInfoboxProps
from openapi_client.models.v1_result_infobox_props_infobox_inner import V1ResultInfoboxPropsInfoboxInner
from openapi_client.models.v1_result_search import V1ResultSearch
from openapi_client.models.v1_result_search_image import V1ResultSearchImage
from openapi_client.models.v1_result_search_props import V1ResultSearchProps
from openapi_client.models.v1_result_search_props_thumbnail_image import V1ResultSearchPropsThumbnailImage
from openapi_client.models.v1_result_video import V1ResultVideo
from openapi_client.models.v1_result_video_props import V1ResultVideoProps
from openapi_client.models.v1_result_web_archive import V1ResultWebArchive
from openapi_client.models.v1_result_web_archive_props import V1ResultWebArchiveProps
