# coding: utf-8

"""
    Kagi API

    The search API provides programmatic access to data that powers our search results & more. Kagi APIs  We have the following APIs available. ### Commercial  - Kagi Search API (invite only at the moment) - Web and News Enrichment API (public, exposes Kagi's own indexes Teclis and TinyGem) - Universal Summarizer API (public) - FastGPT API (public)  Quick start for all APIs:  - Get the API key (requires a Kagi account). - Top off your API credits. - Call the API.  ### Free  - Kagi Small Web RSS feed (public)  ### Unofficial Client Libraries  Libraries created by Kagi users and third parties.  - kagigo for Go - FastGPT & Universal Summarizer - kagi-api for Rust - kagi-dotnet for C#/.NET  ### Beta Status  The API is currently in a \"v0\" beta status. Changes will be ongoing, and will be added to the documentation below as features become available.  Use at your own risk, but please reach out to us if you have any questions.  See the Support and Community section for details. ### GitHub Discussions  This is the preferred venue for bug reports and feature requests.  - Bug Reports - Q&A Forum - API Feature Requests  ### Discord Join our Discord! Good for quick questions, chatting about thing you've made with our APIs! 

    The version of the OpenAPI document: 0.0.0
    Contact: support@kagi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.v1_result_adjacent_question import V1ResultAdjacentQuestion
from openapi_client.models.v1_result_infobox import V1ResultInfobox
from openapi_client.models.v1_result_search import V1ResultSearch
from openapi_client.models.v1_result_video import V1ResultVideo
from openapi_client.models.v1_result_web_archive import V1ResultWebArchive
from typing import Optional, Set
from typing_extensions import Self

class SuperSearch200ResponseData(BaseModel):
    """
    SuperSearch200ResponseData
    """ # noqa: E501
    search: Optional[List[V1ResultSearch]] = None
    video: Optional[List[V1ResultVideo]] = None
    adjacent_question: Optional[List[V1ResultAdjacentQuestion]] = None
    infobox: Optional[List[V1ResultInfobox]] = None
    web_archive: Optional[List[V1ResultWebArchive]] = None
    __properties: ClassVar[List[str]] = ["search", "video", "adjacent_question", "infobox", "web_archive"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SuperSearch200ResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in search (list)
        _items = []
        if self.search:
            for _item_search in self.search:
                if _item_search:
                    _items.append(_item_search.to_dict())
            _dict['search'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in video (list)
        _items = []
        if self.video:
            for _item_video in self.video:
                if _item_video:
                    _items.append(_item_video.to_dict())
            _dict['video'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in adjacent_question (list)
        _items = []
        if self.adjacent_question:
            for _item_adjacent_question in self.adjacent_question:
                if _item_adjacent_question:
                    _items.append(_item_adjacent_question.to_dict())
            _dict['adjacent_question'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in infobox (list)
        _items = []
        if self.infobox:
            for _item_infobox in self.infobox:
                if _item_infobox:
                    _items.append(_item_infobox.to_dict())
            _dict['infobox'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in web_archive (list)
        _items = []
        if self.web_archive:
            for _item_web_archive in self.web_archive:
                if _item_web_archive:
                    _items.append(_item_web_archive.to_dict())
            _dict['web_archive'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SuperSearch200ResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "search": [V1ResultSearch.from_dict(_item) for _item in obj["search"]] if obj.get("search") is not None else None,
            "video": [V1ResultVideo.from_dict(_item) for _item in obj["video"]] if obj.get("video") is not None else None,
            "adjacent_question": [V1ResultAdjacentQuestion.from_dict(_item) for _item in obj["adjacent_question"]] if obj.get("adjacent_question") is not None else None,
            "infobox": [V1ResultInfobox.from_dict(_item) for _item in obj["infobox"]] if obj.get("infobox") is not None else None,
            "web_archive": [V1ResultWebArchive.from_dict(_item) for _item in obj["web_archive"]] if obj.get("web_archive") is not None else None
        })
        return _obj


